services:
  - type: web
    name: ai-crypto-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ai_crypto_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MOCK_MODE
        value: "false"
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
